spring.profile=dev
#spring.application.name=project-api
server.port=8081
server.servlet.context-path=/api
#springfox.documentation.swagger-ui.path=/caminho-personalizado
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/local
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
driverClassName: org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
